### ISSUE TITLE
div.clearer in css file

### ISSUE THREAD

**Issue by kingatomic** [xoxco/jQuery-Multipage-Form#1]
I noticed that one of the final inserted elements is a div of class "clearer", which doesn't appear in the multipage css file.  In my own test implementation I found this when the nav buttons were falling out beneath my parent div.  I fixed this with the following css:

```
div.clearer{
    display: block;
    visibility: hidden;
    clear: both;
    height:0;
    border-width:0;
    margin:0;
    padding:0;
}
```

**Comment by benbrown** [comment]
Awesome, thanks for catching this.  We'll roll it into the next release.
