### ISSUE TITLE
Inserted navigation uses incorrect selector

### ISSUE THREAD

**Issue by kingatomic** [xoxco/jQuery-Multipage-Form#2]
I've been playing with Multipage on a project I'm doing, and was puzzled because what I was seeing wasn't what I saw in the demo.  The Next/Back buttons appeared, but had no text from the legend fields and I wasn't seeing any state information between the buttons.  

I figured out that it's because the navigation div that's automatically appended to the form is given the ID "#multipage_nav" on creation; the rest of the script, however, _builds_ the selector for that div from the id of the form (eg, "#myform_nav") in the many, many instances of 

``` javascript
$(id + '_nav .multipage_next')
```

The reason it works in the demo is because the demo's form ID is _multipage_ :)

Here's my fix (sorry too lazy to fork and branch):

``` javascript
if (settings.generateNavigation) { 
    if (settings.navigationFunction) { 
        settings.navigationFunction($(this).getPages());
    } else {
        // insert navigation
        var id_name = $(this).attr('id');
        $('<div class="multipage_nav" id="'+id_name+'_nav"><a href="#" class="multipage_back" onclick="return  $(\''+id+'\').prevpage();">Back</a><a href="#"  class="multipage_next" onclick="return $(\''+id+'\').nextpage();">Next</a><span class="multipage_state"></span><div class="clearer"></div></div>').insertAfter(this);                    
        //$('<div class="multipage_nav" id="multipage_nav"><a href="#" class="multipage_back" onclick="return  $(\''+id+'\').prevpage();">Back</a><a href="#"  class="multipage_next" onclick="return $(\''+id+'\').nextpage();">Next</a><span class="multipage_state"></span><div class="clearer"></div></div>').insertAfter(this);
    }
}
```

I added the id_name var to capture the ID for brevity's sake when concatenating it into the selector string.

**Comment by DamienBell** [comment]
Hey thanks for the catch.  We made both of those changes.
